package sagex.api.enums;

/**
 * Unofficial SageTV Generated File - Never Edit
 * Generated Date/Time: 25/03/13 8:50 PM
 * See Official Sage Documentation at <a href='http://download.sage.tv/api/sage/api/FavoriteAPIEnum.html'>FavoriteAPIEnum</a>
 * This Generated API is not Affiliated with SageTV.  It is user contributed.
 */
public enum FavoriteAPIEnum {

IsFirstRunsAndReRuns,
IsFirstRunsOnly,
IsReRunsOnly,
IsFirstRuns,
IsReRuns,
IsAutoDelete,
IsDeleteAfterAutomaticConversion,
GetKeepAtMost,
GetFavoriteDescription,
GetFavoriteTitle,
GetFavoriteCategory,
GetFavoriteSubCategory,
GetFavoritePerson,
GetFavoriteRated,
GetFavoritePersonRole,
GetFavoriteYear,
GetFavoriteParentalRating,
GetFavoriteChannel,
GetFavoriteKeyword,
GetFavoriteNetwork,
GetFavoriteTimeslot,
GetStartPadding,
GetStopPadding,
GetFavoriteQuality,
GetFavoriteAutomaticConversionFormat,
GetFavoriteAutomaticConversionDestination,
SetStartPadding,
SetStopPadding,
SetFavoriteQuality,
SetFavoriteAutomaticConversionFormat,
SetFavoriteAutomaticConversionDestination,
CreateFavoritePriority,
ConfirmManualRecordOverFavoritePriority,
SetDontAutodelete,
SetDeleteAfterAutomaticConversion,
SetKeepAtMost,
SetRunStatus,
SetFavoriteTitle,
SetFavoriteCategories,
SetFavoritePerson,
SetFavoriteRated,
SetFavoriteYear,
SetFavoriteParentalRating,
SetFavoriteKeyword,
SetFavoriteChannel,
SetFavoriteNetwork,
SetFavoriteTimeslot,
GetFavoriteForAiring,
DoesFavoriteMatchAiring,
IsFavoriteObject,
UpdateFavorite,
GetFavoriteAirings,
GetFavoriteID,
GetFavoriteForID,
GetFavorites,
RemoveFavorite,
AddFavorite,
GetFavoriteProperty,
SetFavoriteProperty,
GetFavoriteProperties
}
